# Generated by Django 5.2.6 on 2025-10-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
